INSERT INTO patients VALUES (1, 'Maya Thompson', 1);
INSERT INTO appointments VALUES (1, 1, 'Cardiology follow-up', 'Dr. Elena Rivera', '2026-09-18 10:30', 'Episodes of rapid heartbeat and tiredness during daily activities');
INSERT INTO preparation_tasks VALUES
(1,1,'Confirm appointment date and time','complete','2026-09-10'),(2,1,'Add insurance card','complete','2026-09-10'),(3,1,'Add referral document','complete','2026-09-12'),(4,1,'Verify medication list','complete','2026-09-15'),(5,1,'Review allergy information','complete','2026-09-15'),(6,1,'Complete symptom history','complete','2026-09-15'),(7,1,'Upload recent ECG report','not_started','2026-09-15'),(8,1,'Confirm transportation','in_progress','2026-09-17'),(9,1,'Complete clinic intake form','not_started','2026-09-17');
INSERT INTO symptoms VALUES
(1,1,'Rapid heartbeat','2026-07-28',7,'Intermittent; often when climbing stairs','patient_entered'),(2,1,'Tiredness','2026-07-20',5,'Most afternoons','patient_entered'),(3,1,'Lightheadedness','2026-08-04',4,'Twice after standing quickly','patient_entered');
INSERT INTO medications VALUES (1,1,'Metoprolol succinate','25 mg','Once daily','active'),(2,1,'Atorvastatin','10 mg','At bedtime','active'),(3,1,'Vitamin D3','1000 IU','Once daily','active'),(4,1,'Cetirizine','10 mg','As needed','active');
INSERT INTO documents VALUES (1,1,'Cardiology referral','Referral','Lakeside Primary Care','Page 1 · Referral reason'),(2,1,'Synthetic blood panel','Lab result','Northstar Demo Labs','Page 1 · Follow-up'),(3,1,'Primary care visit summary','Visit note','Lakeside Primary Care','Page 2 · Plan'),(4,1,'Demo insurance card','Insurance','Sample Health Plan','Front image');
INSERT INTO questions VALUES (1,1,'What possible causes are you considering for these episodes?',1),(2,1,'What information would help narrow down the cause?',1),(3,1,'Should I continue my current medicines before any tests?',1),(4,1,'What should I track if another episode happens?',0),(5,1,'Which warning signs should prompt urgent care?',0),(6,1,'When should I schedule follow-up?',0);

